Repository MCP-Foundation/Local-Buzz, pull requests merged in 2020-05, with the labels that each got.

#5 added guide to contribute to repo.
  CONTRIBUTING.md
  README.md
Labels: documentation

#30 Main hompage components
  src/components/HomePage/About.js
  src/components/HomePage/HomePage.js
  src/components/HomePage/Tag.js
Labels: front-end

#31 added methods for user creation, authentication and verification.
  src/api/controllers/auth.js
  src/api/package.json
Labels: back-end

#39 Routes Setup
  src/api/controllers/posts.js
  src/api/controllers/users.js
  src/api/index.js
  src/api/models/Posts.js
  src/api/routes/router.js
  yarn.lock
Labels: back-end

#40 React router
  package.json
  src/App.js
Labels: front-end

#44 Forum component
  src/App.js
  src/components/Forum/Forum.css
  src/components/Forum/Forum.js
  src/components/Forum/ForumHeader.js
  src/components/Forum/ForumPosts.js
  src/components/Forum/Post.js
  src/components/Forum/SearchTags.js
  src/components/Navigation/Navigation.jsx
Labels: front-end

#45 Login and Register forms
  src/App.js
  src/components/authentication/Login/Login.js
  src/components/authentication/Login/LoginForm.js
  src/components/authentication/Register/Register.js
  src/components/authentication/Register/RegisterForm.js
  src/components/authentication/authentication.css
Labels: front-end

#52 Near mvp
  db.js
  package-lock.json
  package.json
  src/api/controllers/auth.js
  src/api/controllers/users.js
  src/api/index.js
  src/api/models/Admin.js
  src/api/models/Posts.js
  src/api/models/Users.js
  src/api/package-lock.json
  src/api/package.json
  src/api/routes/router.js
  src/components/Forum/Forum.css
  src/components/Forum/Forum.js
  src/components/Forum/ForumHeader.js
  src/components/Forum/ForumPosts.js
  src/components/Forum/Post.js
  src/components/Forum/SearchTags.js
  src/components/HomePage/About.js
  src/components/HomePage/Banner.js
  src/components/HomePage/HomePage.css
  src/components/HomePage/HomePage.js
  src/components/HomePage/Tag.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/components/Login/LoginForm.js
  src/components/Logo.js
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
  src/components/Register/Register.css
  src/components/Register/Register.js
  src/components/Register/RegisterForm.js
  yarn.lock
Labels: back-end

#55 Forum component
  src/components/Forum/Post.js
  src/components/Forum/PostForm.js
  src/components/Login/Login.js
  src/components/Login/LoginForm.js
  src/components/Register/Register.js
  src/components/Register/RegisterForm.js
  src/tables.sql
Labels: front-end

#56 Api configuration
  .gitignore
  db.js
  package-lock.json
  package.json
  src/api/controllers/auth.js
  src/api/controllers/posts.js
  src/api/controllers/users.js
  src/api/models/Posts.js
  src/api/models/Users.js
  src/api/package-lock.json
  src/api/routes/router.js
Labels: back-end, bug

#60 Forum component
  .eslintrc.json
  src/api/db.js
  src/api/routes/router.js
  src/components/Forum/Forum.js
  src/components/Forum/ForumHeader.js
  src/components/Forum/PostForm.js
Labels: bug, front-end

#62 near finalization of api routes.
  src/api/controllers/posts.js
  src/api/controllers/users.js
  src/api/db.js
  src/api/routes/router.js
  src/components/Forum/PostForm.js
  src/components/Register/RegisterForm.js
Labels: back-end, bug, front-end

#61 Package.json updated
  db.js
  package.json
  src/api/controllers/posts.js
  src/api/db.js
  src/api/index.js
  src/api/routes/router.js
  yarn.lock
Labels: bug

#64 models slight update
  src/api/controllers/users.js
  src/api/index.js
  src/api/models/Admins.js
  src/api/models/Posts.js
  src/api/routes/router.js
  src/api/yarn.lock
  src/components/Navigation/Navigation.jsx
Labels: bug

#65 changed route names, cleaned up some errors.
  src/api/controllers/posts.js
  src/api/controllers/users.js
  src/api/models/Posts.js
  src/api/routes/router.js
  src/components/Forum/ForumHeader.js
  src/components/Forum/ForumPosts.js
  src/components/Login/LoginForm.js
  src/components/Register/RegisterForm.js
Labels: back-end, bug

#67 Api
  package.json
  src/api/controllers/posts.js
  src/api/models/Post.js
  src/components/Forum/ForumPosts.js
  src/components/Login/Login.js
  src/components/Login/LoginForm.js
  src/components/Navigation/Navigation.jsx
Labels: bug

#69 Api
  .gitignore
  Client/package-lock.json
  Client/package.json
  Client/public/favicon.ico
  Client/public/index.html
  Client/public/robots.txt
  Client/src/App.css
  Client/src/App.js
  Client/src/App.test.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostForm.js
  Client/src/components/Forum/SearchTags.js
  Client/src/components/HomePage/About.js
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.css
  Client/src/components/HomePage/HomePage.js
  Client/src/components/HomePage/Tag.js
  Client/src/components/Login/Login.css
  Client/src/components/Login/Login.js
  Client/src/components/Login/LoginForm.js
  Client/src/components/Logo.js
  Client/src/components/Navigation/Navigation.css
  Client/src/components/Navigation/Navigation.jsx
  Client/src/components/Register/Register.css
  Client/src/components/Register/Register.js
  Client/src/components/Register/RegisterForm.js
  Client/src/index.css
  Client/src/index.js
  Client/src/serviceWorker.js
  Client/src/setupTests.js
  Client/src/tables.sql
  Client/yarn.lock
  README.md
  Server/controllers/posts.js
  Server/controllers/users.js
  Server/index.js
  Server/models/Admins.js
  Server/models/Post.js
  Server/models/Posts.js
  Server/models/Users.js
  Server/package-lock.json
  Server/package.json
  Server/routes/router.js
  Server/yarn.lock
  db.js
  src/api/db.js
  src/api/index.js
Labels: back-end, bug

#77 Post component Update
  Client/.eslintrc.js
  Client/package-lock.json
  Client/package.json
  Client/public/index.html
  Client/src/App.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostForm.js
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.js
  Server/controllers/posts.js
  Server/models/Posts.js
  Server/models/Users.js
  Server/routes/router.js
Labels: bug, enhancement, front-end

#79 Styled components
  Client/package-lock.json
  Client/package.json
  Client/src/App.css
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.css
  Client/src/components/Login/Login.js
  Client/src/components/Login/LoginForm.js
  Client/src/components/Register/Register.js
  Client/src/components/Register/RegisterForm.js
  Client/src/index.css
  Client/yarn.lock
  Server/routes/router.js
Labels: enhancement, front-end

#86 working model from the morning.
  Client/package-lock.json
  Client/src/components/Profile/UserPost.js
  Server/controllers/posts.js
  Server/models/Posts.js
  Server/routes/router.js
Labels: back-end, bug

#98 Add modal to forum
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumHeader.js
Labels: front-end

#101 Post Component update
  Client/package.json
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/Post.js
Labels: enhancement, front-end

#103 Model
  Client/src/App.js
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.js
  Client/src/components/Login/LoginForm.js
  Client/src/components/Navigation/Navigation.jsx
  Client/src/components/Register/RegisterForm.js
  Client/src/contexts/userContext.js
  Client/src/tables.sql
  Server/controllers/posts.js
  Server/controllers/users.js
  Server/models/Posts.js
  Server/models/Users.js
  Server/routes/router.js
Labels: back-end, enhancement

#104 edited schema to include avatar section.
  Client/src/components/Login/LoginForm.js
  Client/src/components/Register/RegisterForm.js
  Client/src/tables.sql
  Server/controllers/users.js
  Server/models/Users.js
Labels: enhancement

#105 fetched info for post view and post comments, adjusted router to allo…
  Client/src/App.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.js
  Server/controllers/posts.js
  Server/models/Posts.js
  Server/routes/router.js
Labels: back-end, enhancement

#106 Knex+migrations
  Client/yarn.lock
  Server/migrations/20200525202046_create-users.js
  Server/migrations/20200525203017_create-posts.js
  Server/migrations/20200525203319_create-comments.js
  Server/migrations/20200525203552_create-admins.js
  Server/package.json
  Server/yarn.lock
Labels: back-end

#107 Created avatar form in sign up
  Client/src/components/Register/AvatarForm.js
  Client/src/components/Register/Register.js
  Client/src/components/Register/RegisterForm.js
Labels: enhancement, front-end

#108 finalized views for components.
  Client/package-lock.json
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/Forum/Post.js
  Server/package-lock.json
Labels: enhancement

#111 comments work, users can register.
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.css
  Client/src/components/Forum/PostView.js
  Client/src/components/Register/Register.js
  Client/src/components/Register/RegisterForm.js
  Server/controllers/posts.js
  Server/controllers/users.js
  Server/models/Posts.js
  Server/models/Users.js
  Server/routes/router.js
Labels: bug

#112 Register Form
  Client/src/components/Register/AvatarForm.js
  Client/src/components/Register/Register.js
  Client/src/components/Register/RegisterForm.js
  Server/controllers/users.js
  Server/models/Users.js
Labels: back-end, front-end

#118 changed around how likes are handled. Added migration for new likes t…
  Server/controllers/likes.js
  Server/controllers/posts.js
  Server/migrations/20200521192805_create_likes_table.js
  Server/models/Likes.js
  Server/models/Posts.js
  Server/routes/router.js
Labels: back-end, enhancement

#119 Liking posts
  Client/src/components/Register/AvatarForm.js
  Client/src/tables.sql
  Server/controllers/likes.js
  Server/controllers/users.js
  Server/routes/router.js
Labels: back-end, front-end

#123 Liking posts in Forum
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Post.js
Labels: front-end

#127 likes are now from the current logged in user rather than a random user.
  Client/src/components/Forum/Post.js
  Client/src/contexts/profileContext.js
  Server/controllers/users.js
  Server/models/Users.js
  Server/routes/router.js
Labels: back-end

#130 Homepage styling
  Client/src/components/Forum/Post.js
  Client/src/components/HomePage/About.js
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.css
  Client/src/components/HomePage/HomePage.js
  Client/src/components/HomePage/Tag.js
  Client/src/components/Profile/UserPost.js
Labels: bug, front-end

#134 made changes to forum and homepage
  Client/src/components/Forum/Comment.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.css
  Client/src/components/Forum/PostView.js
  Client/src/components/Forum/SearchTags.js
  Client/src/components/Forum/UserPost.js
  Client/src/components/HomePage/About.js
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.css
  Client/src/components/HomePage/HomePage.js
  Client/src/components/HomePage/Tag.js
  Client/src/components/Profile/UserPost.js
  Client/src/components/Register/AvatarForm.js
  Client/src/components/Register/RegisterForm.js
  Server/controllers/likes.js
  Server/controllers/posts.js
  Server/controllers/users.js
  Server/routes/router.js
Labels: back-end, bug, enhancement, front-end

#137 Like button bug
  Client/src/components/Forum/Comment.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.css
  Client/src/components/Forum/PostView.js
  Client/src/components/Forum/UserPost.js
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.js
  Server/controllers/likes.js
  Server/models/Likes.js
  Server/routes/router.js
Labels: back-end, bug, front-end

#139 created like button component for posts
  Client/src/components/LikeButton/LikePostButton.js
Labels: bug, front-end

#141 added forum as protected route.
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/Post.js
  Client/src/components/Navigation/Navigation.jsx
  Server/controllers/posts.js
  Server/index.js
  Server/models/Posts.js
  Server/routes/likesRouter.js
  Server/routes/postRouter.js
  Server/routes/router.js
  Server/routes/userRouter.js
Labels: bug

#151 Account page
  Client/src/components/Forum/PostView.js
  Client/src/components/Profile/Introduction.jsx
  Client/src/components/Profile/Profile.css
  Client/src/components/Profile/UserPost.js
Labels: bug, enhancement, front-end

#152 re-added create a comment/create a post using new routes.
  Server/routes/postRouter.js
Labels: back-end, bug

#154 Homepage and navbar styling
  Client/src/components/Footer/Footer.css
  Client/src/components/Footer/Footer.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.js
  Client/src/components/HomePage/About.js
  Client/src/components/HomePage/Banner.js
  Client/src/components/HomePage/HomePage.css
  Client/src/components/HomePage/HomePage.js
  Client/src/components/HomePage/Tag.js
  Client/src/components/Login/LoginForm.js
  Client/src/components/Logo.js
  Client/src/components/Logo/Logo.js
  Client/src/components/Logo/localbuzzBlue.png
  Client/src/components/Logo/localbuzzRed.png
  Client/src/components/Logo/localbuzzWhite.png
  Client/src/components/Logo/localbuzzYellow.png
  Client/src/components/Navigation/Navigation.css
  Client/src/components/Navigation/Navigation.jsx
  Client/src/components/Profile/Profile.css
  Client/src/index.js
Labels: bug, enhancement, front-end

#153 Filter
  Client/src/App.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/Forum/Post.js
  Client/src/components/Forum/PostView.js
  Client/src/components/Navigation/Navigation.css
  Client/src/components/Navigation/Navigation.jsx
  Client/src/components/Register/RegisterForm.js
  Client/src/contexts/tagContext.js
  Server/controllers/users.js
Labels: enhancement, front-end

#155 fixed bug in Forum for rendering all posts
  Client/src/components/Footer/Footer.css
  Client/src/components/Footer/Footer.js
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/Forum.js
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/ForumPosts.js
  Client/src/components/HomePage/Tag.js
  Client/src/components/Login/Login.css
  Client/src/components/Login/LoginForm.js
  Client/src/components/Register/Register.css
  Client/src/components/Register/Register.js
  Client/src/components/Register/RegisterForm.js
  Client/src/contexts/tagContext.js
Labels: bug, front-end

#160 added styling to posts
  Client/src/components/Forum/Forum.css
  Client/src/components/Forum/ForumHeader.js
  Client/src/components/Forum/Post.js
  Client/src/components/Navigation/Navigation.jsx
Labels: enhancement, front-end
